// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart_Delivery_Management_System.Data;

#nullable disable

namespace Smart_Delivery_Management_System.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    [Migration("20251210232040_SeedUsersNew")]
    partial class SeedUsersNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smart_Delivery_Management_System.Models.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Couriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Name = "David Shapiro",
                            PhoneNumber = "0501234567",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Name = "Ella Friedman",
                            PhoneNumber = "0502345678",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = false,
                            Name = "Frank Levy",
                            PhoneNumber = "0503456789",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Smart_Delivery_Management_System.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DropoffAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffAddress = "Tel Aviv, Rothschild 10",
                            PickupAddress = "Tel Aviv, Dizengoff 1",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            CourierId = 1,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffAddress = "Jerusalem, King George 20",
                            PickupAddress = "Jerusalem, Jaffa 5",
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = 3,
                            CourierId = 2,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffAddress = "Haifa, Herzl 15",
                            PickupAddress = "Haifa, Ben Gurion 3",
                            Status = "InProgress"
                        });
                });

            modelBuilder.Entity("Smart_Delivery_Management_System.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            FullName = "Alice Cohen",
                            PasswordHash = "123456",
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            FullName = "Bob Levi",
                            PasswordHash = "987456",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            FullName = "Charlie Katz",
                            PasswordHash = "111111",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("Smart_Delivery_Management_System.Models.Courier", b =>
                {
                    b.HasOne("Smart_Delivery_Management_System.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Smart_Delivery_Management_System.Models.Courier", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Delivery_Management_System.Models.Delivery", b =>
                {
                    b.HasOne("Smart_Delivery_Management_System.Models.Courier", "Courier")
                        .WithMany("Deliveries")
                        .HasForeignKey("CourierId");

                    b.Navigation("Courier");
                });

            modelBuilder.Entity("Smart_Delivery_Management_System.Models.Courier", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
